
name: CI
on: [push, pull_request]

jobs:
  test-all-crates:
    name: Test on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # automatic cache for  Cargo/target
      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Sanity (see files)
        run: pwd && ls -la

      - name: Check formatting
        run: cargo fmt --all -- --check

      # later change for `cargo clippy --all-targets --all-features -- -D warnings`
      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --all --verbose

      - name: Test
        run: cargo test --all --verbose

